# DigitalOcean App Platform Configuration
# Este archivo permite versionar la configuración de tu app en App Platform

name: newtube-prod
region: nyc

# Configuración de la aplicación Next.js
services:
  - name: web
    github:
      repo: tu-usuario/tu-repositorio
      branch: main
      deploy_on_push: true
    
    # Configuración de build y runtime
    build_command: npm run build
    run_command: npm start
    
    # Variables de entorno - Estas se pueden configurar también desde la UI
    # Se recomienda usar la UI para variables sensibles (secrets)
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: ${_APP_URL}  # Variable automática de DigitalOcean
    
    # Recursos
    instance_count: 1
    instance_size_slug: professional-xs  # Recomendado para producción: professional-xs (1GB RAM, $12/mes)
    # Opciones disponibles:
    # - basic-xxs: 512MB RAM, $5/mes (desarrollo)
    # - basic-xs: 1GB RAM, $12/mes (producción pequeña)
    # - professional-xs: 1GB RAM, $12/mes (producción - recomendado)
    # - professional-s: 2GB RAM, $24/mes (producción mediana)
    
    # Health checks
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Rutas
    routes:
      - path: /
    
    # Variables de entorno que se deben configurar en la UI (secrets)
    # Estas son referencias - debes agregarlas manualmente en App Platform:
    # - DATABASE_URL
    # - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    # - CLERK_SECRET_KEY
    # - CLERK_SIGNING_SECRET
    # - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    # - STRIPE_SECRET_KEY
    # - STRIPE_WEBHOOK_SECRET
    # - MUX_TOKEN_ID
    # - MUX_TOKEN_SECRET
    # - MUX_WEBHOOK_SECRET
    # - UPLOADTHING_TOKEN
    # - UPLOADTHING_SECRET
    # - UPSTASH_REDIS_REST_URL
    # - UPSTASH_REDIS_REST_TOKEN
    # - SENTRY_ORG
    # - SENTRY_PROJECT
    # - SENTRY_AUTH_TOKEN
    # - NEXT_PUBLIC_SENTRY_DSN

# Nota: Para usar este archivo, importa tu repositorio y DigitalOcean lo detectará automáticamente
# o usa el CLI de DigitalOcean: doctl apps create --spec app.yaml

